workflows:
  my-workflow:
    instance_type: mac_mini
    max_build_duration: 15
    

    scripts:
      - name: Build Android APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/**/*.apk
      

    triggering:
      events:
        - push
      branch_patterns: 
        - pattern: master
          include: false
      cancel_previous_builds: true
